import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <span className={styles.description}>
          <p>
             Goal Buddy
          </p>
          <div>
            <a>
              <Image
                alt="Sunshine Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </span>

        <div className={styles.center}>
          <p> To sign up for daily affirmations to help achieve your goals to be sent to you via text message, all you 
        need to do is:
        <br></br>
        <br></br>
        1. Give us your name and phone number
        <br></br>
        <br></br>
        2. List your top 3 goals
        <br></br>
        <br></br>
        3. Indicate what time of the day you want to receive the text
        <br></br>
        <br></br>
        That's it!
        </p>
        </div>
        <form action = "https://docs.google.com/spreadsheets/d/1HtBHjh6cH0AXkaZb7hH-aGvog5l1oRGYlkZgejYrfrI/edit#gid=0" method = "post">
          <div className={styles.grid}>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "first">First Name:
              <input type = "text" id = "first" name = "first" required/>
            </h2>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "last">Last Name:
              <input type = "text" id = "last" name = "last" required />
            </h2>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "goal_1">First Goal:
              <input type = "text" id = "goal_1" name = "goal_1" />
            </h2>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "goal_2">Second Goal:
              <input type = "text" id = "goal_2" name = "goal_2" />
            </h2>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "goal_3">Third Goal:
              <input type = "text" id = "goal_3" name = "goal_3" />
            </h2>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "number">Phone Number:
              <input type = "number" id = "number" name = "number"
              required minlength = "10" maxlength = "10" pattern = "[0-9]"
              title = "Please only input the numbers, not including any special characters"/>
              <p className= {styles.card}>
                Please only input numbers, no hyphons
              </p>
            </h2>
            <h2 className= {styles.card}
              target="_blank"
              rel="noopener noreferrer"
              label for = "time">Time of Day:
              <input type = "time" id = "time" name = "time" />
            </h2>
            <button type = "submit">Submit</button>
          </div>  
         </form>
      </main>
    </>
  )
}
